on:
  push:
    branches:
      - 'mw/rk35/pinenote-next-t1'
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compile the pinenote kernel
    steps:
      - name: Docker-based compilation
        id: compile-kernel-in-docker
        uses: m-weigand/linux@description
      - uses: actions/upload-artifact@v3
        with:
          name: pinenote_kernel_modules_dtb
          path: /home/runner/work/_temp/_github_home/pack/
